apport-retrace: install base-files first
On Ubuntu 24.04 (noble):

```
$ divide-by-zero
$ mkdir -p "$PWD/sandbox-config/Ubuntu 24.04"
$ echo noble > "$PWD/sandbox-config/Ubuntu 24.04/codename"
$ cat > "$PWD/sandbox-config/Ubuntu 24.04/sources.list" <<EOF
deb http://de.archive.ubuntu.com/ubuntu/ noble main universe
deb-src http://de.archive.ubuntu.com/ubuntu/ noble main universe
EOF
$ apport-retrace -v -S "$PWD/sandbox-config" --gdb-sandbox -C "$PWD/sandbox-cache" /var/crash/_usr_bin_divide-by-zero.1000.crash
[...]
Extracting downloaded debs...
ERROR: [Errno 2] No such file or directory: '/tmp/apport_sandbox_8x704zqr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2'
```

This commit squashes commit 52560e691cb1 ("apport-retrace: install
base-files first") and the fix-up commit aaa13fcf928c ("apport-retrace:
avoid installing base-files unconditionally").

Bug-Ubuntu: https://launchpad.net/bugs/2067120
Fixes: 52560e691cb1 ("apport-retrace: install base-files first")