problem_report: enforce some keys to always have str values in __setitem__
plasmashell crashed on the system, and when Apport tried to upload the
problem report, whoopsie-upload-all crashed:

```
INFO:root:Collecting info for /var/crash/_usr_bin_plasmashell.1000.crash...
ERROR: hook /usr/share/apport/general-hooks/generic.py crashed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport/report.py", line 314, in _run_hook
    symb["add_info"](report, ui)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/share/apport/general-hooks/generic.py", line 70, in add_info
    for lib in re.finditer(r"\s(/[^ ]+\.so[.0-9]*)$", report["ProcMaps"], re.M):
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/re/__init__.py", line 285, in finditer
    return _compile(pattern, flags).finditer(string)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/usr/share/apport/whoopsie-upload-all", line 246, in <module>
    main()
    ~~~~^^
  File "/usr/share/apport/whoopsie-upload-all", line 228, in main
    stamps = collect_info()
  File "/usr/share/apport/whoopsie-upload-all", line 162, in collect_info
    res = process_report(r)
  File "/usr/share/apport/whoopsie-upload-all", line 112, in process_report
    r.add_gdb_info()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1057, in add_gdb_info
    addr_signature = self.crash_signature_addresses()
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1797, in crash_signature_addresses
    if self["ProcMaps"].startswith("Error: "):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

The `ProcMaps` field in the crash report has following last lines:

```
 7f8e5d61b000-7f8e5d61e000 r-xp 00002000 fc:00 19081540                   /usr/lib/x86_64-linux-gnu/qt6/plugins/kf6/packagestructure/plasma_wallpaper.so
 7f8e5d61e000-7f8e5d61f000 r--p 00005000 fc:00 19081540                   /usr/lib/x86_64-linux-gnu/qt6/plugins/kf6/packagestructure/plasma_wallpaper.so
 7f8e5d61f000-7f8e5d620000 r--p 00005000 fc:00 190815U\0\0
```

So string value for `ProcMaps` seems to be truncated.
whoopsie-upload-all opens the crash file and keeps the value as `bytes`
because it contains null characters at the end.

The value for `ProcMaps` should always be a string. There are other
fields that are expected to be string as well.

Prevent setting those keys to non-string values. This should result in
more consistent `ProblemReport` object instances and ensured that
loading the problem report will work. This can be accompanied by type
hints in a future commit.

Bug: https://launchpad.net/bugs/2146806